name: Auto PR and Merge

on:
  push:
    branches-ignore:
      - main

permissions:
  pull-requests: write
  contents: write

jobs:
  auto-pr-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create PR, Merge, and Delete Branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Memeriksa apakah Pull Request sudah ada untuk branch ${GITHUB_REF_NAME}..."
          PR_EXISTS=$(gh pr list --head ${GITHUB_REF_NAME} --base main --json number --jq 'length')
          
          if [ "$PR_EXISTS" -eq "0" ]; then
            echo "Membuat Pull Request..."
            gh pr create -B main -H ${GITHUB_REF_NAME} --title "Auto PR: ${GITHUB_REF_NAME}" --body "Pull request ini dibuat dan di-merge secara otomatis oleh GitHub Actions saat terjadi push ke branch ${GITHUB_REF_NAME}."
          else
            echo "Pull Request sudah ada."
          fi

          echo "Melakukan Merge Pull Request dan Menghapus Branch..."
          # Menggunakan squash merge. Jika Anda lebih suka merge commit biasa, ganti --squash menjadi --merge
          gh pr merge ${GITHUB_REF_NAME} --squash --delete-branch
